models.py
import base64
from datetime import datetime
from Crypto.Protocol.KDF import scrypt
from Crypto.Random import get_random_bytes
from cryptography.fernet import Fernet
from flask_login import LoginManager, UserMixin
from werkzeug.security import generate_password_hash
from app import db


def encrypt(data, postkey):
    return Fernet(postkey).encrypt(bytes(data, 'utf-8'))


def decrypt(data, postkey):
    return Fernet(postkey).decrypt(data).decode("utf-8")


class User(db.Model,  UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False, unique=True)
    password = db.Column(db.String(100), nullable=False)

    # crypto key for user's posts
    postkey = db.Column(db.BLOB)

    registered_on = db.Column(db.DateTime, nullable=False)
    last_logged_in = db.Column(db.DateTime, nullable=True)
    current_logged_in = db.Column(db.DateTime, nullable=True)

    blogs = db.relationship('Post')

    def __init__(self, username, password):
        self.username = username
        self.password = generate_password_hash(password)
        self.postkey = base64.urlsafe_b64encode(scrypt(password, str(get_random_bytes(32)), 32, N=2 ** 14, r=8, p=1))
        self.registered_on = datetime.now()
        self.last_logged_in = None
        self.current_logged_in = None


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, db.ForeignKey(User.username), nullable=True)
    created = db.Column(db.DateTime, nullable=False)
    title = db.Column(db.Text, nullable=False, default=False)
    body = db.Column(db.Text, nullable=False, default=False)

    def __init__(self, username, title, body, postkey):
        self.username = username
        self.created = datetime.now()
        self.title = encrypt(title, postkey)
        self.body = encrypt(body, postkey)

    def update_post(self, title, body, postkey):
        self.title = encrypt(title, postkey)
        self.body = encrypt(body, postkey)
        db.session.commit()

    def view_post(self, postkey):
        self.title = decrypt(self.title, postkey)
        self.body = decrypt(self.body, postkey)


def init_db():

    db.drop_all()
    db.create_all()
    new_user = User(username='user1@test.com', password='mysecretpassword')
    db.session.add(new_user)
    db.session.commit()

blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required


class PostForm(FlaskForm):
    title = StringField(validators=[Required()])
    body = TextAreaField(validators=[Required()])
    submit = SubmitField()

users/forms.py
import re
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import Required, Email, Length, EqualTo, ValidationError


def character_check(form,field):
    excluded_chars="*?"
    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(f"Character {char} is not allowed")


class RegisterForm(FlaskForm):
    username = StringField(validators=[Required(), Email()])
    password = PasswordField(validators=[Required(), Length(min=8, max=15, message='Password must be between '
                                                                                   '8 and 15 characters in length'),character_check])
    confirm_password = PasswordField(validators=[Required(), EqualTo('password', message='Both password fields'
                                                                                         'must be equal!')])
    submit = SubmitField()

    def validate_password(self, passwrod):
        p = re.compile(r'(?=.*\d)(?=.*[A-Z])')
        if not p.match(self.password.data):
            raise ValidationError("Password must contain at least 1 digit and 1 uppercase letter.")


class LoginForm(FlaskForm):
    username = StringField(validators=[Required(), Email()])
    password = PasswordField(validators=[Required()])
    submit = SubmitField()

app.py
import socket
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SECRET_KEY'] = 'LongAndRandomSecretKey'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///blog.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)






@app.route('/')
def index():
    return render_template('index.html')


if __name__ == '__main__':
    my_host = "127.0.0.1"
    free_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    free_socket.bind((my_host, 0))
    free_socket.listen(5)
    free_port = free_socket.getsockname()[1]
    free_socket.close()


    login_manager = LoginManager()
    login_manager.login_view = 'users.login'
    login_manager.init_app(app)

    from models import User

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    # blueprints
    from users.views import users_blueprint
    from blog.views import blog_blueprint

    app.register_blueprint(users_blueprint)
    app.register_blueprint(blog_blueprint)

    app.run(host=my_host, port=free_port, debug=True)

blog/views.py
from flask import Blueprint, render_template
from sqlalchemy import desc
from app import db
from blog.forms import PostForm
from models import Post, User


blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

user = User.query.first()
postkey = user.postkey


@blog_blueprint.route('/blog')
def blog():
    posts = Post.query.order_by(desc('id')).all()

    for p in posts:
        p.view_post(postkey)

    return render_template('blog.html', posts=posts)


@blog_blueprint.route('/create', methods=('GET', 'POST'))
def create():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(username=None, title=form.title.data, body=form.body.data, postkey=postkey)

        db.session.add(new_post)
        db.session.commit()

        return blog()
    return render_template('create.html', form=form)


@blog_blueprint.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
    post = Post.query.filter_by(id=id).first()
    if not post:
        return render_template('500.html')

    form = PostForm()

    if form.validate_on_submit():
        post.update_post(form.title.data, form.body.data, postkey)

        return blog()

    post.view_post(postkey)

    form.title.data = post.title
    form.body.data = post.body

    return render_template('update.html', form=form)


@blog_blueprint.route('/<int:id>/delete')
def delete(id):
    Post.query.filter_by(id=id).delete()
    db.session.commit()

    return blog()

users/views.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
from app import db
from models import User
from users.forms import RegisterForm, LoginForm
from blog.views import blog


users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user:
            flash('Username address already exists')
            return render_template('register.html', form=form)

        new_user = User(username=form.username.data, password=form.password.data)

        db.session.add(new_user)
        db.session.commit()

        print(request.form.get('username'))
        print(request.form.get('password'))

        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if not user or not check_password_hash(user.password, form.password.data):
            flash('Please check your login details and try again')

            return render_template('login.html', form=form)

        login_user(user)

        user.last_logged_in = user.current_logged_in
        user.current_logged_in = datetime.now()
        db.session.add(user)
        db.session.commit()

        return blog()

    return render_template('login.html', form = form)

@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031 Blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>

<style>
    .table {
        margin-left: auto;
        margin-right: auto;
    }
</style>

<section class="hero is-primary is-fullheight">

    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('index') }}" class="navbar-item">
                            Home
                        </a>
                        <a href="{{ url_for('blog.blog') }}" class="navbar-item">
                            Blog
                        </a>
                        <a href="{{ url_for('blog.create') }}" class="navbar-item" >
                            Create Post
                        </a>
                        <a href="{{ url_for('users.register') }}" class="navbar-item">
                            Sign Up
                        </a>
                        <a href="{{ url_for('users.login') }}" class="navbar-item">
                            Login
                        </a>
                        <a href="{{ url_for('users.logout') }}" class="navbar-item">
                            Log out
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</section>
</body>

</html>

templates/blog.html
{% extends "base.html" %}

{% block content %}
 
    <div class="column is-6 is-offset-3">
        <h1 class="title is-1">Posts</h1>
        <div class="box">
            {% for post in posts %}
                <article class="media">
                    <div class="media-content">
                        <div class="content">
                            <h1>{{ post.title }}</h1>
                            <p>
                                <strong>{{ post.username }}</strong>
                                <small>{{ post.created.strftime('%d-%m-%Y') }}</small>
                                <br>
                                {{ post.body }}
                                <br>
                            <div id="navbarMenuHeroA" class="navbar-menu">
                                <div class="navbar-start">
                                    <a class="navbar-item" href="{{ url_for('blog.update', id=post.id) }}">Update</a>
                                    <a class="navbar-item" href="{{ url_for('blog.delete', id=post.id) }}">Delete</a>
                                </div>
                            </div>
                            </p>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/create.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h3 class="title is-3">Create Post</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.title(class="input", placeholder="Title") }}
                        {% for error in form.title.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.body(class="textarea", placeholder="Body") }}
                        {% for error in form.body.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <h1 class="title is-1">CSC2031 Security & Programming Paradigms</h1>

    <h2 class="subtitle is-2">Welcome to the CSC2031 Blog</h2>

{% endblock %}

templates/login.html
{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
                <form method="POST">
                    <div class="field">
                        {{ form.csrf_token() }}
                        <div class="control">
                            {{ form.username(class="input", placeholder="Username") }}
                            {% for error in form.username.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.password(class="input", placeholder="Password") }}
                            {% for error in form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>

                    <div>
                        {{ form.submit(class="button is-info is-centered") }}
                    </div>
                </form>

        </div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}

            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.username(class="input", placeholder="Username") }}
                        {%  for error in form.username.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for errror in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/update.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h3 class="title is-3">Update Post</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.title(class="input") }}
                        {% for error in form.title.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control" >
                        {{ form.body(class="textarea") }}
                        {% for error in form.body.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}